// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNu9zUQe3Envj8s5K1mk05Us01YVPKovI',
    appId: '1:893875377271:web:89b4494194c753005c6272',
    messagingSenderId: '893875377271',
    projectId: 'fishpal-57e60',
    authDomain: 'fishpal-57e60.firebaseapp.com',
    databaseURL: 'https://fishpal-57e60-default-rtdb.firebaseio.com',
    storageBucket: 'fishpal-57e60.firebasestorage.app',
    measurementId: 'G-GNJNKC8WFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLO2ehrDA3TWjoqx-EhyK21ENT0IL0u30',
    appId: '1:893875377271:android:b12593141c38bbb35c6272',
    messagingSenderId: '893875377271',
    projectId: 'fishpal-57e60',
    databaseURL: 'https://fishpal-57e60-default-rtdb.firebaseio.com',
    storageBucket: 'fishpal-57e60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb_7DHq20lNQBDwNByR5kSsRtM-bd-G4E',
    appId: '1:893875377271:ios:55fb0f22aff23aa15c6272',
    messagingSenderId: '893875377271',
    projectId: 'fishpal-57e60',
    databaseURL: 'https://fishpal-57e60-default-rtdb.firebaseio.com',
    storageBucket: 'fishpal-57e60.firebasestorage.app',
    iosBundleId: 'com.example.myfishpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb_7DHq20lNQBDwNByR5kSsRtM-bd-G4E',
    appId: '1:893875377271:ios:55fb0f22aff23aa15c6272',
    messagingSenderId: '893875377271',
    projectId: 'fishpal-57e60',
    databaseURL: 'https://fishpal-57e60-default-rtdb.firebaseio.com',
    storageBucket: 'fishpal-57e60.firebasestorage.app',
    iosBundleId: 'com.example.myfishpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNu9zUQe3Envj8s5K1mk05Us01YVPKovI',
    appId: '1:893875377271:web:0882c4b0ffc354e45c6272',
    messagingSenderId: '893875377271',
    projectId: 'fishpal-57e60',
    authDomain: 'fishpal-57e60.firebaseapp.com',
    databaseURL: 'https://fishpal-57e60-default-rtdb.firebaseio.com',
    storageBucket: 'fishpal-57e60.firebasestorage.app',
    measurementId: 'G-2NY5S9L716',
  );
}
